### ISSUE TITLE
Authentication mechanism

### ISSUE THREAD

**Issue by diocas** [sciencemesh/cs3api4lab#10]
This issue is to discuss the authentication of the extension, as requested in the last meeting.

## 1. Context
Allowing the use of username+password can be maintained in the config, although having passwords in plain text is not recommended. But this might be useful for local dev (we should give a warning if the user uses this).

The best way to authenticate should be via OIDC/oAuth tokens. These tokens expire so we need to allow a configurable way of updating them (since different authentication methods might have different ways of doing things). For SWAN, for example, it might be better that we read the EOS oAuth file*, since it's already updated and is being used by the FUSE mount. For other installations without EOS, maybe calling an external service or asking JupyterHub might be the solution (which is how in SWAN we renew the EOS oAuth file: we retrieve the latest auth information from JH** and write to a file. For SWAN I propose reading this file to avoid having 2 processes asking JH for the same information).

## 2. Implementation
I suggest adding a configuration to our ContentsManager that receives a method. This method should receive the `userid` + the current - in use - `token`, and will return a new `token` that should be used instead. Then we can call this method right before we create the `AuthenticateRequest`.
Why do we pass the current token? Because the renewal might need some extra information from it, or it can check wether it's still valid.

We can provide some example functions, like one that reads from JH**, another that reads a file and another that reads the EOS special format file*. This way, in the configuration we don't need to implement these basic cases, we just import and use one of those.

@JarCz please let me know if you need any clarification!

---
\* The EOS oAuth file has the following format: "_oauth2:<OAUTH_TOKEN>:<OAUTH_INSPECTION_ENDPOINT>_".

** If you're using [oauthenticator](https://github.com/jupyterhub/oauthenticator), you can access the user oauth token by querying the user endpoint of JupyterHub, like so (from inside the Jupyter terminal):
```bash
$ curl -H "Authorization: token $JUPYTERHUB_API_TOKEN" $JUPYTERHUB_API_URL/users/$NB_USER
```
```json
{
    "kind": "user",
    "name": "username",
    "admin": true,
    "groups": [],
    "server": "/user/username/",
    "pending": null,
    "created": "2020-08-31T09:31:24.638244Z",
    "last_activity": "2020-08-31T10:43:46.033379Z",
    "servers": {
        "": {
            (...)
        }
    },
    "auth_state": {
        "access_token": "blablabla",
        "refresh_token": "blablabla",
        "oauth_user": {
            "sub": "username",
            "cern_uid": 00000,
            "preferred_username": "username",
            "cern_gid": 00000,
            "given_name": "Diogo",
            "cern_preferred_language": "EN",
            "home_institute": "CERN",
            "cern_person_id": 821079,
            "name": "Diogo Castro",
            "cern_mail_upn": "mail@mail.com",
            "family_name": "Castro",
            "email": "my.email@mail.com",
            "cern_upn": "username"
        },
        "scope": [
            "oidc-cern-profile",
            "oidc-email",
            "oidc-cern-login-info",
            "oidc-client-id"
        ]
    }
}
```
In our KeyCloak authenticator, based on `oauthenticator`, we implement the JupyterHub function that updates this information automatically. But this is not implemented by default by the other `oauthenticator`'s.

**Comment by JarCz** [comment]
I agree the best is to create an interface and specific class to implement the authentication type. 

I think, now we need auth types:
- Basic Riva auth - login/pass best for dev
- Riva token - reads Riva token from ENV or file, for JupyterHub integration. 
- EOS - I need some example of EOS environment, maybe Can I use this example https://github.com/cernbox/kuboxed?

The config section has information with type uses and extra config for a specific type.

**Comment by diocas** [comment]
The EOS option I mentioned was reading a file. The only difference is that the file is not a json file, or whatever. Is a text file that has "oauth2:<OAUTH_TOKEN>:<OAUTH_INSPECTION_ENDPOINT>" written (so we just need to parse the string and split by `:`). But proceed with the rest, I don't mind implementing that function.

ps: there's nothing in kuboxed that will help. So ignore it.

**Comment by diocas** [comment]
Btw, what I wrote before is not true: JH does not expose the oauth token via its API to non admin users. I've created a ticket with them to see if it can (SWAN does it, but because we did a workaround).
