### ISSUE TITLE
Error parsing container's date

### ISSUE THREAD

**Issue by mateusz-garlacz** [sciencemesh/cs3api4lab#121]
@ishank011

When I was testing the extension on CERNBox I encountered the followig error when I tried to list /eos/user/a :

```
File "/home/magc/round4/cs3api4lab/cs3api4lab/api/cs3apismanager.py", line 341, in _convert_container_to_base_model
        created = datetime.fromtimestamp(cs3_model.mtime.seconds, tz=tz.UTC)
    ValueError: year 4435543 is out of range
```
The culprit of this is the /alwang directory, which contains invalid date:
```
type: RESOURCE_TYPE_CONTAINER
id
{   storage_id: "eoshome-a"   opaque_id: "8058013" }
checksum {
}
etag: "\"7af49d:139910077999520.007\""
mime_type: "httpd/unix-directory"
mtime
{   seconds: 139910077999520  nanos: 7350896 }
path: "/alwang"
permission_set {
}
size: 717628417147
owner
{   idp: "https://auth.cern.ch/auth/realms/cern"   opaque_id: "alwang"   type: USER_TYPE_PRIMARY }
arbitrary_metadata {
  metadata
{     key: "user.acl"     value: ""   }
}
```
which contains timestamp in microseconds and not in seconds. I will introduce a workaround in the extension for this becasue this prevents from directories navigation, but please fix and validate this folder and other occurences.

 @diocas

**Comment by diocas** [comment]
@ishank011 identified this as a EOS bug and reported it to the devs. But yes, we should have sanitization checks.

**Comment by diocas** [comment]
@ishank011 @gmgigi96 was this solved?
Either way, this has been sanitized on our side, so I'll close the ticket.
