### ISSUE TITLE
ContentsManager

### ISSUE THREAD

**Issue by diocas** [sciencemesh/cs3api4lab#2]
Subtask of #1 

These modules requires a client for the CS3APIs. An example can be seen here: https://github.com/cs3org/wopiserver

Requirements:
- Configurable CS3API endpoint
    - Use of config/env variable to set the endpoint. This will allow connections to a remote instance if the user is remote (using SWAN via a federated share)

**Comment by diocas** [comment]
@JarCz you can clone this project and set the configurations as mentioned in the readme. If you need help setting up jupyter, let me know. For setting up Reva you already know how to do it, right?

**Comment by JarCz** [comment]
Yes, I've some knowledge about Reva.

**Comment by diocas** [comment]
@JarCz I've added the methods that require implementation. Please try to run Jupyterlab with the required configurations (described in the readme) to see if it works (by working, I mean fails. You are supposed to see in the logs all the `NotImplementedError` exceptions popping up).

I've also added the methods for the checkpoints but ignore them for now. I will create a separate issue for those.

### Documentation:
- Base class: [notebook/services/contents/manager.py](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/manager.py)
- Jupyter implementation for a local FS: [notebook/services/contents/largefilemanager.py](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/largefilemanager.py) and [notebook/services/contents/filemanager.py](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py)
