### ISSUE TITLE
Do not require setting all environment variables

### ISSUE THREAD

**Issue by michzimny** [sciencemesh/cs3api4lab#26]
When running in Docker, it is required to set all ([currently ca. 13](https://github.com/sciencemesh/cs3api4lab/blob/master/reva_config.env)) environment variables for a container. If any variable is missing, the error is raised:

```
raise ValueError(f"Unable to read {name} from environment variables")
```

In this approach, if a new env variable was added, it would be always a backward-incompatible change as it would require users of the Docker image to adopt their scripts and provide a value for the new variable.

It is widely-adopted practice to have default values for all (most of?) the variables specified in the Docker image. Then, when running a container, one would only set a few variables that need to be changed from the defaults.

**Comment by diocas** [comment]
This was the previous behavior but was changed in #24. I agree a default config should exist, especially given the backward-compatibility issues you mention.
But there are still some variables (like the reva url) which I'm not sure which (if any) default values they should have.

**Comment by michzimny** [comment]
I would leave reva url without any default value. Moreover, if reva url is not provided, I would suggest that plugin does not start (if feasible), instead of silently starting without incorrect configuration.

**Comment by mateusz-garlacz** [comment]
@michzimny if the url will not have default value, then the reva credentials should also be empty?

**Comment by diocas** [comment]
With default values:
"auth_token_validity",
"endpoint",
"home_dir",
"chunk_size",
"secure_channel", (should we make this false, and then we accept cert and key as empty?)
"client_cert",
"client_key",
"ca_cert",
"login_type"

Without default values, which will fail if not provided:
"reva_host",
"client_id",
"client_secret", (this should not be needed if the login type is oauth)

What do you think? @michzimny @mateusz-garlacz

**Comment by michzimny** [comment]
Correct!

**Comment by mateusz-garlacz** [comment]
So I if I am not mistaken the priority order for config values should be:
- config file
- default docker image variables
- env variables
Right?

**Comment by michzimny** [comment]
I would say that env variables should always have the highest priority, i.e. if any variable is set, it takes precedence over any other configuration sources.

And a default value should have always the lowest priority, i.e. it is used if no configuration source provided value for this variable.
