### ISSUE TITLE
FilesViewer for Jupyterlab

### ISSUE THREAD

**Issue by diocas** [sciencemesh/cs3api4lab#4]
We need to develop a lab extension to expose the remaining functionality implemented in #3 in the web UI. Functionality like sharing via right click, see the shares of the user, see other mountpoints (i.e Projects), etc.

If possible, we should extend the functionality of the upstream extension, just adding the strictly necessary functionality on top without having to copy all of it.

TODO: create mockups of possible interface to implement.

**Comment by piotrWichlinskiSoftwaremind** [comment]
Hey, for starters we can investigate how to register basic command in the context menu on the file system widget to get basic file info on the right mouse click. As I was going through the documentation I have seen this should be possible. @diocas what do you think?

**Comment by diocas** [comment]
@piotrWichlinskiSoftwaremind please go ahead! It should be possible to register those actions even without having to rewrite the extension, but what we need to check is if we can inherit from that extension, and just add stuff on top. 

This will be necessary as we probably need to put some dropdown to change from "my files", "shared with me", "shared by me", etc, while keeping the rest of the ui (to avoid having to duplicate and maintain this code).

**Comment by diocas** [comment]
Hi @piotrWichlinskiSoftwaremind,
So, as mentioned in the meeting, I suggest you have a look into the [GDrive extension](https://github.com/jupyterlab/jupyterlab-google-drive).
This extension looks like it does exactly what I wanted: it reuses all the JupyterLab components for listing files, creating the menus etc, but changes only the API access to, instead of contacting the Jupyter ContentsManager, it contacts the Google API. In our case, we don't need to change the API, we should re-use the upstream one. Instead, we just need to add the functionality to enable sharing.

## Suggestion for the UI

![img1](https://user-images.githubusercontent.com/2589871/87483886-284e2e00-c635-11ea-8aa7-2c50b04d0df6.png)

The UI is just like the normal Lab file viewer, so this should be re-used. The differences are:
 * Name and icon: this should be configurable. If I connect to CERNBox, I want this to appear. If I connect to OwnCloud, I might want a different name and icon.
* Tabs: for switching between the user files and the sharing menu (see bellow). Ps: ignore the projects tab for now.
* The sharing button: the right click menu should show entries to share a folder or file via private share (with a known username) or via public links. But we should also add a sharing button on the top to allow users to share the current folder.
* Footer with the usage stats and number of files/folder hidden. We can deal with showing the hidden files later.

![2  cernbox 2](https://user-images.githubusercontent.com/2589871/87484282-1620bf80-c636-11ea-9122-59092b0011c7.png)

The share tab should show what was shared with me *and* by me. I imagined this as an "accordion": if you click in "share by me", the "shared with me" collapses.
We also need to show pending shares, so that the user can accept or reject them. I will try to come up with the design and update the image.

![2  cernbox 3](https://user-images.githubusercontent.com/2589871/87484290-18831980-c636-11ea-9855-34067a228c76.png)

In the right click menu, the user should also have the option to see "File info". This will show all the metadata.

![2  cernbox 4](https://user-images.githubusercontent.com/2589871/87484294-191bb000-c636-11ea-9003-fbb7662286b5.png)

Clicking sharing, both from the right click menu and the top bar, should show the sharing dialog. I lost some changes in my image and will try to update it and create one for the public links.

There are many other things I think we should add. But for now, having just this functionality would be extremely good.
Please let me know if you need any clarification.
